server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: personas-service
          uri: lb://personas-service
          predicates:
            - Path=/personas/**
        - id: reservas-service
          uri: lb://reservas-service
          predicates:
            - Path=/reservas/**
        - id: facturas-service
          uri: lb://facturas-service
          predicates:
            - Path=/factura/**